modLoader = "javafml"
loaderVersion = "[35,)"
#issueTrackerURL = ""
license = "GNU GPLv3"

[[mods]]
modId = "mcndi"
version = "${version}"
displayName = "MC NDI REMASTERED"
authors = "Polo_1245"
description = '''
MC NDI Remastered is a Minecraft modification that enhances your streaming experience by providing direct support for outputting Minecraft gameplay as NDI sources.
'''
logoFile = ""
